export const SET_TOKEN = "SET_TOKEN";
export const SET_USERNAME = "SET_USERNAME";
export const SET_ROUTER_NAME = "SET_ROUTER_NAME";
export const SET_CARS_LIST_STATUS = "SET_CARS_LIST_STATUS";
export const SET_CARS_LIST_REQUEST = "SET_CARS_LIST_REQUEST";
export const SELF_LOCATION = "SELF_LOCATION";
export const SET_PARKING_ID = "SET_PARKING_ID";
